### ISSUE TITLE
Add `babylond` binary in the release page

### ISSUE THREAD

**Issue by bap2pecs** [babylonlabs-io/babylon#221]
this can be handy when people don't want to install GO and build from source code. similar to what we have on https://github.com/babylonlabs-io/babylon-contract/releases (i.e. the `.wasm` binaries)

@SebastianElvis wdyt?

**Comment by SebastianElvis** [comment]
We have recently added goreleaser that is triggered upon every tag ([ref](https://github.com/babylonlabs-io/babylon/blob/main/.github/workflows/goreleaser.yml)). From the next tag there should be binaries.
