### ISSUE TITLE
Moving voting power table from btcstaking module to finality module

### ISSUE THREAD

**Issue by gitferry** [babylonlabs-io/babylon#24]
[context](https://github.com/babylonlabs-io/babylon/pull/12#discussion_r1709161951)

**Comment by SebastianElvis** [comment]
Tasks breakdown

- [ ] https://github.com/babylonlabs-io/babylon/pull/216
- [ ] move all relevant queries to `x/finality`
- [ ] move voting power dist cache / voting power table to `x/finality`
