### ISSUE TITLE
chore: add event to failed Msgs in queue

### ISSUE THREAD

**Issue by RafilxTenfen** [babylonlabs-io/babylon#66]
## Summary

Currently that are a few msgs that are run at then of each epoch
and affect the cosmos-sdk validator set 
`[QueuedMessage_MsgCreateValidator, QueuedMessage_MsgDelegate, 
QueuedMessage_MsgUndelegate, QueuedMessage_MsgBeginRedelegate,
QueuedMessage_MsgCancelUnbondingDelegation]`

But if any of those msgs fail to run, nothing is thrown for the user to query and
verify the reason it failed.

## Problem Definition

No feedback for the user if his transaction failed.

## Proposal

Add one or multiple new event types if any error happens during [`HandleQueuedMsg`](https://github.com/babylonlabs-io/babylon/blob/5f8af8ced17d24f3f0c6172293cd37fb3d055807/x/epoching/keeper/epoch_msg_queue.go#L110)
that details the reason it failed, so the user can at least query for it when the msg is processed at the end of an epoch

**Comment by SebastianElvis** [comment]
> Add one or multiple new event types if any error happens during [`HandleQueuedMsg`](https://github.com/babylonlabs-io/babylon/blob/5f8af8ced17d24f3f0c6172293cd37fb3d055807/x/epoching/keeper/epoch_msg_queue.go#L110)
> that details the reason it failed, so the user can at least query for it when the msg is processed at the end of an epoch

Some events will be [emitted](https://github.com/babylonlabs-io/babylon/blob/00330e49b17768eec9373cbddd74ae60d9336be3/x/epoching/abci.go#L92-L113) if `HandleQueuedMsg` over a message returns an error, and the event already includes the error message. Does this mean this proposal is more or less already implemented?

**Comment by RafilxTenfen** [comment]
@SebastianElvis Oh yes, thanks! I had not seen this
