### ISSUE TITLE
BTC-timestamping public randomness

### ISSUE THREAD

**Issue by gitferry** [babylonlabs-io/babylon#8]
In the Babylon Bitcoin-staking protocol, finality providers are required to commit a range of public randomness before sending finality signatures. However, if the honest majority assumption does not hold, the attacker might commit conflicting randomness on forks and escape from being slashed with performing equivocation attack. Therefore, BTC-timestamping is introduced to address the issue.

Required changes from Babylon:
* Introduce epoch to each randomness commit to enforce that the committed randomness takes effect only after the relevant epoch is finalized
* Do not assign voting power to finality providers that do not have finalized randomness for a particular block

**Comment by KonradStaniec** [comment]
ref: https://github.com/babylonlabs-io/pm/issues/11
